# Generated by Django 4.1.3 on 2023-02-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cynthia_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('arrival_date', models.DateField()),
                ('leave_date', models.DateField()),
                ('comment', models.CharField(max_length=500)),
            ],
        ),
    ]
